import { parseTerms } from './terms.mjs';
// Korean readings of the upstream brand identifiers. Official English names and
// upstream tags are also searchable; these readings do not rename the API.
export const brands = parseTerms(`
4chan=포챈|abstract=앱스트랙트|adobe-after-effects=어도비 애프터 이펙트|adobe-illustrator=어도비 일러스트레이터|adobe-indesign=어도비 인디자인|adobe-photoshop=어도비 포토샵|adobe-premiere=어도비 프리미어|adobe-xd=어도비 엑스디|adobe=어도비|adonis-js=아도니스 제이에스|airbnb=에어비앤비|airtable=에어테이블|algolia=알골리아|alipay=알리페이|alpine-js=알파인 제이에스
amazon=아마존|amd=에이엠디|amie=에이미|amigo=아미고|among-us=어몽 어스|android=안드로이드|angular=앵귤러|ansible=앤서블|ao3=아카이브 오브 아워 오운|appgallery=앱갤러리|apple-arcade=애플 아케이드|apple-news=애플 뉴스|apple-podcast=애플 팟캐스트|apple=애플|appstore=앱스토어|arc=아크|asana=아사나|astro=아스트로|audible=오더블|auth0=오스제로|aws=아마존 웹 서비스|azure=애저
backbone=백본|badoo=바두|baidu=바이두|bandcamp=밴드캠프|bandlab=밴드랩|beats=비츠|bebo=비보|behance=비핸스|bilibili=빌리빌리|binance=바이낸스|bing=빙|bitbucket=비트버킷|blackberry=블랙베리|blender=블렌더|blogger=블로거|bluesky=블루스카이|booking=부킹닷컴|bootstrap=부트스트랩|bulma=불마|bumble=범블|bunpo=분포
c-sharp=씨샵|cake=케이크|cakephp=케이크 피에이치피|campaignmonitor=캠페인 모니터|carbon=카본|cashapp=캐시앱|chrome=크롬|cinema-4d=시네마 포디|citymapper=시티매퍼|cloudflare=클라우드플레어|codecov=코드코브|codepen=코드펜|codesandbox=코드샌드박스|cohost=코호스트|coinbase=코인베이스|comedy-central=코미디 센트럴|coreos=코어오에스|couchdb=카우치디비|couchsurfing=카우치서핑|cpp=씨플러스플러스|craft=크래프트|crunchbase=크런치베이스|css3=씨에스에스 삼|ctemplar=씨템플러|cucumber=큐컴버|cupra=쿠프라|cypress=사이프러스
d3=디쓰리|databricks=데이터브릭스|days-counter=디데이 카운터|dcos=디씨오에스|debian=데비안|deezer=디저|deliveroo=딜리버루|deno=디노|denodo=데노도|deviantart=디비언트아트|digg=디그|dingtalk=딩톡|discord=디스코드|disney=디즈니|disqus=디스커스|django=장고|docker=도커|doctrine=독트린|dolby-digital=돌비 디지털|douban=더우반|dribbble=드리블|dropbox=드롭박스|drops=드롭스|drupal=드루팔
edge=엣지|elastic=엘라스틱|electronic-arts=일렉트로닉 아츠|ember=엠버|envato=엔바토|etsy=엣시|evernote=에버노트|facebook=페이스북|feedly=피들리|figma=피그마|filezilla=파일질라|finder=파인더|firebase=파이어베이스|firefox=파이어폭스|fiverr=파이버|flickr=플리커|flightradar24=플라이트레이더 이십사|flipboard=플립보드|flutter=플러터|fortnite=포트나이트|foursquare=포스퀘어|framer-motion=프레이머 모션|framer=프레이머|funimation=퍼니메이션
gatsby=개츠비|git=깃|github-copilot=깃허브 코파일럿|github=깃허브|gitlab=깃랩|gmail=지메일|golang=고 언어|google-analytics=구글 애널리틱스|google-big-query=구글 빅쿼리|google-drive=구글 드라이브|google-fit=구글 피트니스|google-home=구글 홈|google-maps=구글 지도|google-one=구글 원|google-photos=구글 포토|google-play=구글 플레이|google-podcasts=구글 팟캐스트|google=구글|grammarly=그래머리|graphql=그래프큐엘|gravatar=그라바타|grindr=그라인더|guardian=가디언|gumroad=검로드
hackerrank=해커랭크|hbo=에이치비오|headlessui=헤드리스 유아이|hexo=헥소|hipchat=힙챗|html5=에이치티엠엘 오|inertia=이너시아|infakt=인팩트|instagram=인스타그램|intercom=인터컴|itch=잇치|javascript=자바스크립트|jira=지라|juejin=쥐에진|kakao-talk=카카오톡|kbin=케이빈|kick=킥|kickstarter=킥스타터|kotlin=코틀린|laravel=라라벨|lastfm=라스트에프엠|leetcode=리트코드|letterboxd=레터박스|line=라인|linkedin=링크드인|linktree=링크트리|linqpad=링크패드|livewire=라이브와이어|loom=룸
mailgun=메일건|mantine=맨타인|mastercard=마스터카드|mastodon=마스토돈|matrix=매트릭스|mcdonalds=맥도날드|medium=미디엄|meetup=밋업|mercedes=메르세데스|messenger=메신저|meta=메타|metabrainz=메타브레인즈|minecraft=마인크래프트|miniprogram=미니프로그램|mixpanel=믹스패널|monday=먼데이닷컴|mongodb=몽고디비|my-oppo=마이 오포|mysql=마이에스큐엘|national-geographic=내셔널 지오그래픽|nem=넴|netbeans=넷빈즈|netease-music=넷이즈 뮤직|netflix=넷플릭스|nexo=넥소
nextcloud=넥스트클라우드|nextjs=넥스트제이에스|nodejs=노드제이에스|nord-vpn=노드브이피엔|notion=노션|npm=엔피엠|nuxt=넉스트|nytimes=뉴욕타임스|oauth=오어스|office=오피스|ok-ru=오드노클라스니키|onedrive=원드라이브|onlyfans=온리팬스|open-source=오픈 소스|openai=오픈에이아이|openvpn=오픈브이피엔|opera=오페라|pagekit=페이지킷|parsinta=파르신타|patreon=패트리온|paypal=페이팔|paypay=페이페이|peanut=피넛|pepsi=펩시|php=피에이치피|picsart=픽스아트|pinterest=핀터레스트
planetscale=플래닛스케일|pnpm=피엔피엠|pocket=포켓|polymer=폴리머|powershell=파워셸|printables=프린터블스|prisma=프리즈마|producthunt=프로덕트 헌트|pushbullet=푸시불릿|pushover=푸시오버|python=파이썬|qq=큐큐|radix-ui=래딕스 유아이|react-native=리액트 네이티브|react=리액트|reason=리즌|reddit=레딧|redhat=레드햇|redux=리덕스|revolut=레볼루트|rumble=럼블|rust=러스트|safari=사파리|samsungpass=삼성 패스|sass=사스|sentry=센트리
sharik=샤리크|shazam=샤잠|shopee=쇼피|signal=시그널|sketch=스케치|skype=스카이프|slack=슬랙|snapchat=스냅챗|snapseed=스냅시드|snowflake=스노우플레이크|socket-io=소켓 아이오|solidjs=솔리드제이에스|soundcloud=사운드클라우드|spacehey=스페이스헤이|speedtest=스피드테스트|spotify=스포티파이|stackoverflow=스택 오버플로|stackshare=스택셰어|steam=스팀|stellar=스텔라|stocktwits=스톡트윗|storj=스토리지|storybook=스토리북|storytel=스토리텔|strava=스트라바|stripe=스트라이프|sublime-text=서브라임 텍스트
sugarizer=슈거라이저|supabase=수파베이스|superhuman=슈퍼휴먼|supernova=슈퍼노바|surfshark=서프샤크|svelte=스벨트|swift=스위프트|symfony=심포니|tabler=테이블러|tabnine=탭나인|tailwind=테일윈드|taobao=타오바오|teams=팀즈|ted=테드|telegram=텔레그램|terraform=테라폼|tesla=테슬라|tether=테더|thingiverse=씽기버스|threads=스레드|threejs=쓰리제이에스|tidal=타이달|tiktok=틱톡|tinder=틴더|topbuzz=탑버즈|torchain=토르체인|toyota=토요타|trello=트렐로|tripadvisor=트립어드바이저|tumblr=텀블러
twilio=트윌리오|twitch=트위치|twitter=트위터|typescript=타입스크립트|uber=우버|ubuntu=우분투|unity=유니티|unsplash=언스플래시|upwork=업워크|valorant=발로란트|vechain=비체인|vercel=버셀|vimeo=비메오|vinted=빈티드|visa=비자|visual-studio=비주얼 스튜디오|vite=바이트|vivaldi=비발디|vk=브이케이|vlc=브이엘씨|volkswagen=폭스바겐|vsco=비스코|vscode=비주얼 스튜디오 코드|vue=뷰|walmart=월마트|waze=웨이즈|webflow=웹플로|wechat=위챗|weibo=웨이보|whatsapp=왓츠앱
wikipedia=위키피디아|windows=윈도우|windy=윈디|wish=위시|wix=윅스|wordpress=워드프레스|x=엑스|xamarin=자마린|xbox=엑스박스|xdeep=엑스딥|xing=싱|yahoo=야후|yandex=얀덱스|yarn=얀|yatse=야체|ycombinator=와이 콤비네이터|youtube-kids=유튜브 키즈|youtube=유튜브|zalando=잘란도|zapier=재피어|zeit=자이트|zhihu=즈후|zoom=줌|zulip=줄립|zwift=즈위프트
`);
