import { parseTerms } from './terms.mjs';
// Reviewed Korean terms used to compose the official icon families. Missing terms
// fail generation; English-name fallbacks are intentionally not used.
const lines = `
abacus=주판|abc=가나다 알파벳|access=접근|accessible=접근성|acorn=도토리|acrobatic=곡예|activity=활동|ad=광고|add=추가|address=주소|adjustments=조절|aerial=공중|affiliate=제휴|afghani=아프가니|agender=무성별|agent=에이전트|agents=에이전트들|ai=인공지능|aid=응급 처치|air=공기|airpods=에어팟|airport=공항|airtag=에어태그
alarm=알람|album=앨범|alert=경고|alias=별칭|alien=외계인|align=정렬|all=전체|alpha=알파|alphabet=알파벳|alt=대체|ambulance=구급차|american=미국식|ammeter=전류계|ampersand=앤드 기호|analytics=분석 통계|analyze=분석|anchor=닻|and=그리고 논리곱|androgyne=안드로진|angle=각도|angry=화남|ankh=앙크|annoyed=짜증|antenna=안테나|aperture=조리개|api=응용 프로그래밍 인터페이스
app=앱|apple=사과|apps=앱 목록|aquarius=물병자리|arab=아랍|arabic=아랍 문자|arc=원호|arch=아치|archery=양궁|archive=보관함|arcs=원호들|area=영역|aries=양자리|armchair=안락의자|arrival=도착|arrow=화살표|arrows=화살표들|artboard=아트보드|article=기사|ascending=오름차순|aspect=가로세로 비율|assembly=조립|asset=자산|asterisk=별표|at=골뱅이|atom=원자|audio=오디오
augmented=증강|australian=호주|auth=인증|auto=자동|autofit=자동 맞춤|automatic=자동|automation=자동화|automotive=자동차|average=평균|avg=평균|avocado=아보카도|award=수상|axe=도끼|axis=축|baby=아기|back=뒤로|background=배경|backhoe=굴착기|backpack=배낭|backslash=역슬래시|backspace=백스페이스|backward=뒤쪽|badge=배지|badges=배지들
bag=가방|baguette=바게트|bahraini=바레인|baht=바트|balancer=분산기|ball=공|balloon=풍선|ballpen=볼펜|ban=금지|banana=바나나|bandage=반창고|bangla=벵골 문자|bank=은행|banknote=지폐|bar=막대|barbell=바벨|barcode=바코드|barrel=통|barrier=차단기|bars=막대들|baseball=야구|baseline=기준선|basket=바구니|basketball=농구|bat=박쥐|bath=욕조|battery=배터리
beach=해변|beam=광선|bear=곰|bed=침대|beer=맥주|bell=종 알림|beta=베타|bevel=모서리 깎기|bezier=베지에 곡선|bib=턱받이|bible=성경|big=큰|bigender=바이젠더|bike=자전거|billiard=당구|binary=이진수|binoculars=쌍안경|biohazard=생물학적 위험|bishop=비숍|bitcoin=비트코인|blade=칼날|bleach=표백|blend=혼합|blender=믹서기|blind=시각 장애|blob=덩어리
block=블록|blockquote=인용문|blocks=블록들|bluetooth=블루투스|blur=흐림|board=보드|body=몸|bold=굵게|bolt=번개|bomb=폭탄|bone=뼈|bong=물담배|book=책|bookmark=책갈피|bookmarks=책갈피들|books=책들|boom=폭발|border=테두리|bot=봇|both=양쪽|bottle=병|bottom=아래쪽|bottombar=하단 표시줄|bounce=튀기|bow=활|bowl=그릇|bowling=볼링|box=상자|boy=소년
braces=중괄호|brackets=대괄호|braille=점자|brain=뇌|branch=분기|bread=빵|break=분리|bridge=다리|briefcase=서류 가방|brightness=밝기|broadcast=방송|broken=깨짐|browser=브라우저|brunei=브루나이|brush=붓|bubble=말풍선|bucket=양동이|buffer=버퍼|bug=버그|bugs=벌레들|building=건물|buildings=건물들|bulb=전구|bulk=묶음|bulldozer=불도저|burger=햄버거|burj=부르즈|bus=버스|businessplan=사업 계획|butterfly=나비|by=저작자 표시
cactus=선인장|cake=케이크|calculator=계산기|calendar=달력|call=통화|calling=전화 걸기|camera=카메라|camper=캠핑카|campfire=모닥불|canadian=캐나다|canary=카나리아|cancel=취소|cancer=게자리|candle=양초|candy=사탕|cane=지팡이|cannabis=대마초|cap=모자|capacitor=축전기|capricorn=염소자리|capsule=캡슐|caption=캡션|capture=캡처|car=자동차|carambola=스타프루트|caravan=카라반
card=카드|cardboards=골판지 상자|cards=카드들|caret=방향 삼각형|carousel=회전 목록|carriage=유모차|carrot=당근|cart=장바구니|case=문자 구분|cash=현금|cast=화면 전송|castle=성|cat=고양이|category=분류|cctv=감시 카메라|cell=셀|celsius=섭씨|cent=센트|center=가운데|centered=가운데 정렬|certificate=인증서|chair=의자|chalkboard=칠판|champagne=샴페인|change=변경|changeover=전환|charging=충전
chart=차트|chatbot=챗봇|check=확인|checkbox=체크박스|checkered=체크무늬|checklist=체크리스트|checks=이중 확인|checkup=검진|cheese=치즈|chef=요리사|cherry=체리|chess=체스|chest=가슴|chevron=갈매기표|chevrons=이중 갈매기표|chip=칩|chisel=끌|chlorine=염소|chocolate=초콜릿|chopsticks=젓가락|christianity=기독교|christmas=크리스마스|church=교회|circle=원형|circles=원들|circuit=회로|circus=서커스
cleaner=청소기|clear=지우기|clef=음자리표|click=클릭|cliff=절벽|clipboard=클립보드|clock=시계|clockwise=시계 방향|close=닫기|closed=닫힘|clothes=옷|cloud=구름|clover=클로버|clubs=클로버 무늬|cocktail=칵테일|code=코드|codeblock=코드 블록|coffee=커피|coffin=관|cog=톱니바퀴|cohort=코호트|coin=동전|coins=동전들|collaboration=협업|collage=콜라주|collapse=접기|color=색상|column=열|columns=열들
comet=혜성|command=명령|commit=커밋|commons=공유 저작물|community=커뮤니티|compact=압축형|compare=비교|compass=나침반|complex=복합|components=컴포넌트|computer=컴퓨터|computing=컴퓨팅|conditioning=조절|cone=원뿔|confetti=색종이|config=설정|conflict=충돌|confucius=유교|confused=혼란|congruent=합동|connect=연결|connected=연결됨|connection=연결|contain=포함|container=컨테이너|content=콘텐츠
contract=축소|contrast=대비|control=제어|cooker=조리기|cookie=쿠키|copy=복사|copyleft=카피레프트|copyright=저작권|corner=모서리|corners=모서리들|cos=코사인|cottage=오두막|covariate=공변량|cpu=중앙 처리 장치|cracked=금이 간|crane=크레인|crash=충돌|crazy=흥분|cream=크림|creative=창작|credit=신용|credits=크레딧|cricket=크리켓|crop=자르기|cross=십자가|crosshair=조준선|crown=왕관|crutches=목발|cry=울음|crystal=수정
cube=정육면체|cup=컵|curling=컬링|curly=곱슬|currency=통화|current=전류|cursor=커서|curve=곡선|curved=굽은|cut=잘라내기|cylinder=원기둥|cyrillic=키릴 문자|czech=체코|danish=덴마크|dashboard=대시보드|dashed=파선|data=데이터|database=데이터베이스|deaf=청각 장애|decimal=소수점|decrease=감소|deep=깊은|deer=사슴|delete=삭제|deleted=삭제됨|delivery=배송|delta=델타|demiboy=데미보이|demigirl=데미걸|density=밀도
dental=치과|departure=출발|derivatives=도함수|descending=내림차순|description=설명|deselect=선택 해제|desk=책상|desktop=데스크톱|details=상세|device=기기|devices=기기들|diabolo=디아볼로|diagonal=대각선|dialpad=전화 키패드|diamond=마름모|diamonds=다이아몬드 무늬|diaper=기저귀|dice=주사위|diff=차이|difference=차이|digit=자리 숫자|digital=디지털|dimensions=치수|dinar=디나르|diode=다이오드|dip=하락|direction=방향|directions=길 안내
director=감독|dirham=디르함|disabled=비활성|disc=디스크|discount=할인|dislike=싫어요|distribute=균등 배치|divide=나누기|diving=다이빙|dizzy=어지러움|dna=디엔에이 유전자|dog=개|dogecoin=도지코인|dollar=달러|done=완료|dong=동|donut=도넛|door=문|dot=점|dots=점들|dotted=점선|double=이중|down=아래쪽|download=다운로드|draft=초안|drag=드래그|dragon=용|dram=드람|drill=드릴|drone=드론|drop=방울|droplet=물방울|droplets=물방울들
dry=건조|dryclean=드라이클리닝|dual=이중|due=만기|dumbbell=덤벨|dumpling=만두|duplicate=복제|duration=기간|dynamic=동적|ear=귀|earphone=이어폰|ease=완만한 변화|east=동쪽|eco=친환경|edit=편집|egg=달걀|eggs=달걀들|eiffel=에펠탑|eject=꺼내기|elbow=팔꿈치|electric=전기|electricity=전력|elevator=엘리베이터|email=이메일|emergency=응급|empathize=공감|emphasis=강조|empty=비어 있음|end=끝|engine=엔진|enter=진입|epicene=에피신|equal=같음
eraser=지우개|error=오류|escalator=에스컬레이터|estate=부동산|ethereum=이더리움|euro=유로|event=일정|excel=엑셀|exchange=교환|exclamation=느낌표|exercise=운동|exit=나가기|expand=펼치기|explicit=성인 콘텐츠|export=내보내기|exposure=노출|external=외부|extinguisher=소화기|eye=눈|eyeglass=안경|face=얼굴|factory=공장|fahrenheit=화씨|fall=추락|fan=선풍기|fast=빠른|favicon=파비콘|feather=깃털|female=여성|femme=팜|fence=울타리|ferry=페리
fidget=피젯|field=필드|file=파일|files=파일들|filter=필터|filters=필터들|finger=손가락|fingerprint=지문|fingers=손가락들|fire=불|firetruck=소방차|firewall=방화벽|first=처음|fish=물고기|flag=깃발|flame=불꽃|flare=섬광|flask=플라스크|flat=평평한|flip=뒤집기|float=띄우기|flood=홍수|floor=바닥|floppy=플로피 디스크|flops=플롭스|florin=플로린|flower=꽃|focus=초점|fog=안개|fold=접기|folder=폴더|folders=폴더들|football=축구|footsteps=발자국
forbid=금지|forint=포린트|fork=갈래|forklift=지게차|formatting=서식|forms=양식|fortress=요새|forward=앞으로|fountain=분수|frame=틀|frank=프랑|free=자유|freeze=동결|fridge=냉장고|fried=튀김|friends=친구들|from=시작점|front=앞면|frustum=절두체|full=전체|function=함수|funnel=깔때기|galaxy=은하|game=게임|gamepad=게임패드|garage=차고|garden=정원|gas=가스|gateway=게이트웨이|gauge=계기판|gavel=의사봉
gearbox=기어박스|gemini=쌍둥이자리|gender=성별|genderfluid=젠더플루이드|genderless=무성별|genderqueer=젠더퀴어|generation=생성|gentle=약한|geometry=기하|get=가져오기|ghost=유령|gift=선물|gin=진|git=깃 버전 관리|gizmo=조작 도구|glass=유리잔|glasses=안경|globe=지구본|go=이동|goldenratio=황금비|golf=골프|gourmand=미식가|gps=위성 위치 확인|gpu=그래픽 처리 장치|grab=잡기|gradienter=수평계|grain=알갱이|grammar=문법|grape=포도|graph=그래프|grave=무덤
greater=큼|greek=그리스 문자|green=초록|grid=격자|grill=그릴|grip=손잡이|ground=접지|group=그룹|growth=성장|guarani=과라니|guide=안내|guitar=기타|guyanese=가이아나|gymnastics=체조|half=절반|hammer=망치|hand=손|handball=핸드볼|handshake=악수|hang=걸기|hanger=옷걸이|happy=행복|hash=해시|hat=모자|haze=연무|head=머리|heading=제목|headphones=헤드폰|headset=헤드셋|health=건강|heart=하트|heartbeat=심박|hearts=하트들
hebrew=히브리 문자|height=높이|helicopter=헬리콥터|helmet=헬멧|help=도움말|hemisphere=반구|hermaphrodite=자웅동체|hexagon=육각형|hexagonal=육각|hexagons=육각형들|hide=숨기기|hierarchy=계층|high=높음|highlight=강조 표시|hiragana=히라가나|histogram=히스토그램|history=기록|home=집|hook=갈고리|hoop=후프|horizontal=가로|horse=말|horseshoe=말굽|hospital=병원|hotel=호텔|hour=시간|hourglass=모래시계|hours=시간|hryvnia=흐리우냐|hula=훌라
hydrant=소화전|ice=얼음|iceberg=빙산|icons=아이콘|icosahedron=정이십면체|id=신분증|imac=아이맥|image=이미지|import=가져오기|important=중요|in=안으로|inactive=비활성|inbox=받은 편지함|incoming=들어옴|increase=증가|indent=들여쓰기|index=색인|inductor=인덕터|infinity=무한대|inflight=비행 중|info=정보|infographic=인포그래픽|inner=안쪽|input=입력|insert=삽입|integral=적분|integrals=중적분|intergender=인터젠더|intersect=교집합|into=안으로|inverted=반전
invoice=청구서|invoke=호출|ios=아이오에스|ipad=아이패드|iranian=이란|ironing=다림질|irregular=불규칙|italic=기울임|iteration=반복|jacket=재킷|jar=단지|jetpack=제트팩|jetski=제트스키|jewish=유대교|join=결합|joker=조커|jump=점프|jumping=뛰기|justified=양쪽 맞춤|kanban=칸반|karate=가라테|katakana=가타카나|kayak=카약|kerning=자간 조절|key=열쇠|keyboard=키보드|keyframe=키프레임|keyframes=키프레임들|kid=어린이|king=킹
kip=킵|kit=도구 세트|kitchen=주방|knight=나이트|korean=한국|krone=크로네|label=라벨|ladder=사다리|ladle=국자|lambda=람다|lamp=램프|landing=착륙|landline=유선 전화|landscape=가로 화면|lane=차선|language=언어|laptop=노트북|large=큰|lari=라리|lasso=올가미 선택|last=마지막|latin=라틴 문자|latitude=위도|laurel=월계수|lawn=잔디|layers=레이어|layout=화면 배치|leaf=잎|leak=누출|left=왼쪽|lego=레고|lemon=레몬|lens=렌즈|leo=사자자리
letter=문자|letters=문자들|leu=레우|libra=천칭자리|library=도서관|license=라이선스|lifebuoy=구명환|lift=들어 올리기|lifter=리프트|light=빛|lighter=라이터|lighthouse=등대|lights=조명|like=좋아요|line=선|lines=선들|link=링크|linked=연결됨|lira=리라|list=목록|litecoin=라이트코인|little=작은|live=실시간|load=불러오기|loader=로딩|loading=불러오는 중|location=위치|lock=잠금|locked=잠김|logic=논리|login=로그인|logout=로그아웃|logs=로그|lollipop=막대사탕
longitude=경도|look=보기|loop=반복|love=사랑|low=낮음|lower=소문자|luggage=여행 가방|lungs=폐|machine=기계|macro=매크로|magnet=자석|magnetic=자성|mail=메일|mailbox=우편함|male=남성|man=남자|manat=마나트|manual=수동|many=다중|map=지도|maple=단풍|margin=바깥 여백|mark=표시|markdown=마크다운|marquee=영역 선택|mars=화성|mask=마스크|masks=가면들|massage=마사지|matchstick=성냥|math=수학|matrix=행렬|max=최대|maximize=최대화|measure=측정
meat=고기|medal=메달|medical=의료|medicine=약|medium=중간|meeple=보드게임 말|melon=멜론|menorah=메노라|menu=메뉴|merge=병합|mesh=망|message=메시지|messages=메시지들|meteor=유성|meter=측정기|metronome=메트로놈|michelin=미쉐린|mickey=미키|microfrontends=마이크로 프런트엔드|microphone=마이크|microscope=현미경|microwave=전자레인지|middle=가운데|middleware=미들웨어|military=군대|milk=우유|milkshake=밀크셰이크|min=최소|minimize=최소화|minus=빼기
mist=옅은 안개|mobile=모바일|mobiledata=모바일 데이터|mode=모드|model=모형|monero=모네로|money=돈|moneybag=돈주머니|monitor=모니터|monkeybar=구름사다리|month=월|monument=기념비|mood=표정|moon=달|moped=모페드|mosque=모스크|motion=움직임|motor=모터|motorbike=오토바이|mountain=산|mouse=마우스|moustache=콧수염|move=이동|movie=영화|mower=잔디깎이|mug=머그잔|multiple=여러 개|multiplier=배수|mushroom=버섯|music=음악
naira=나이라|nand=부정 논리곱|nano=나노|narrow=좁은|navbar=탐색 표시줄|navigation=탐색|needle=바늘|nepalese=네팔|nerd=너드|nervous=긴장|network=네트워크|neutral=무표정|neutrois=뉴트로이스|new=새 항목|news=뉴스|next=다음|nfc=근거리 무선 통신|nintendo=닌텐도|no=없음|noise=잡음|none=없음|nor=부정 논리합|north=북쪽|not=부정|notdef=정의되지 않은 문자|note=메모|notebook=공책|notes=메모들|notification=알림|number=숫자|numbers=숫자들|nurse=간호사|nut=너트
object=개체|octagon=팔각형|octahedron=정팔면체|off=꺼짐|old=이전|olympic=올림픽|olympics=올림픽|om=옴 기호|omega=오메가|on=켜짐|once=한 번|one=하나|open=열기|opened=열림|option=옵션|options=옵션들|or=또는 논리합|orbit=궤도|orbits=궤도들|order=순서|orientation=방향|out=밖으로|outbound=외부로|outer=바깥쪽|outgoing=나감|outlet=콘센트|outline=윤곽선|oval=타원|overline=윗줄|paanga=파앙가|package=패키지|packages=패키지들|pacman=팩맨
padding=안쪽 여백|page=페이지|paint=페인트|palette=팔레트|pan=팬|panel=패널|panorama=파노라마|paper=종이|paperclip=종이 클립|parachute=낙하산|parentheses=소괄호|parking=주차|passport=여권|password=비밀번호|patch=패치|pattern=무늬|pause=일시 정지|pavilion=정자|paw=동물 발자국|pay=결제|paywall=유료 장벽|peace=평화|pencil=연필|pendulum=진자|pennant=삼각 깃발|pentagon=오각형|pentagram=오각 별|pepper=고추|percent=퍼센트|percentage=백분율|perfume=향수
perspective=원근|peso=페소|phone=전화|photo=사진|phrases=문구|physiotherapist=물리 치료사|pi=파이|piano=피아노|pick=곡괭이|picker=선택 도구|picnic=소풍|picture=그림|pie=원형 조각|pig=돼지|pilcrow=단락 기호|pile=더미|pill=알약|pillow=베개|pills=알약들|pin=핀|ping=핑|pinned=고정됨|pins=핀들|pipe=관|pipeline=파이프라인|pisces=물고기자리|pitchforks=쇠스랑|pizza=피자|placeholder=자리 표시자|plane=비행기|planet=행성|plant=식물
play=재생|player=플레이어|playlist=재생 목록|playstation=플레이스테이션|plug=플러그|plunger=뚫어뻥|plus=더하기|podium=시상대|point=점|pointer=포인터|points=점들|pokeball=몬스터볼|poker=포커|polarized=극성|polaroid=폴라로이드|polish=폴란드|polygon=다각형|polyhedron=다면체|pong=퐁|poo=대변|pool=수영장|pop=팝|popular=인기|portrait=세로 화면|position=위치|post=보내기|pound=파운드|power=전원|pray=기도|premium=프리미엄|prescription=처방
presentation=발표|press=누르기|prev=이전|printer=프린터|prism=각기둥|prison=감옥|pro=전문가|progress=진행|projecting=투영|projector=프로젝터|prompt=프롬프트|prong=갈래|propeller=프로펠러|protocol=프로토콜|pull=끌어오기|pumpkin=호박|push=밀기|pushbutton=누름 버튼|put=넣기|puzzle=퍼즐|puzzled=당황|pyramid=피라미드|qrcode=큐알 코드|quarter=사분의 일|queen=퀸|question=질문|quetzal=케찰|queue=대기열|quote=인용|quotes=따옴표
rack=선반|radar=레이더|radio=라디오|radioactive=방사능|radius=반지름|rain=비|rainbow=무지개|ramp=경사로|random=무작위|rank=순위|rate=비율|rating=평점|ratio=비율|razor=면도기|real=실제|reality=현실|receipt=영수증|recharging=충전 중|recognition=인식|record=녹화|rectangle=직사각형|rectangular=직사각|recycle=재활용|reduce=줄이기|reduction=축소|reference=참조|refresh=새로고침|refund=환불|regex=정규 표현식|register=등록|registered=등록됨
relation=관계|reload=다시 불러오기|remote=원격|remove=제거|renminbi=인민폐|reorder=순서 변경|repeat=반복|replace=바꾸기|reply=답장|report=보고서|request=요청|reserved=보유|reset=초기화|resistor=저항기|resize=크기 조절|restore=복원|return=돌아가기|rewind=되감기|rhombus=마름모|rial=리알|ribbon=리본|right=오른쪽|rights=권리|ring=고리|ringing=울림|rings=고리들|ripple=물결|riyal=리얄|road=도로|robot=로봇|rocket=로켓|rocking=흔들의자
roll=롤|roller=롤러|rollercoaster=롤러코스터|rook=룩|root=제곱근|rope=밧줄|rosette=로제트|rotary=회전식|rotate=회전|rotated=회전됨|roulette=룰렛|round=둥근|roundabout=회전 교차로|rounded=둥근 모서리|route=경로|router=라우터|row=행|rows=행들|rss=뉴스 피드|rubber=고무|ruble=루블|rufiyaa=루피야|rugby=럭비|ruler=자|run=달리기|runes=룬 문자|rupee=루피|sad=슬픔|sagittarius=궁수자리|sailboat=범선|salad=샐러드|salt=소금
sandbox=샌드박스|sanitizer=손 소독제|sankey=생키|satellite=위성|sausage=소시지|saw=톱|scale=저울|scan=스캔|scary=무서움|scatter=산점도|schema=스키마|school=학교|scissors=가위|scooter=스쿠터|scoreboard=점수판|scorpio=전갈자리|screen=화면|screenshot=화면 캡처|scribble=낙서|script=스크립트|scuba=스쿠버|search=검색|sec=시컨트|secret=비밀|section=구역|seedling=새싹|segway=세그웨이|select=선택|selected=선택됨|selector=선택 도구|selfie=셀카
send=보내기|sensor=센서|seo=검색 엔진 최적화|separator=구분선|server=서버|serverless=서버리스|service=서비스|servicemark=서비스표|settings=설정|shade=그늘|shadow=그림자|shape=도형|shapes=도형들|share=공유|shareplay=동시 재생|sharp=날카로운|shekel=셰켈|shield=방패|shift=전환|ship=배|shirt=셔츠|shoe=신발|shopping=쇼핑|short=짧은|shortcut=바로가기|shovel=삽|show=표시|shredder=문서 파쇄기|shuffle=섞기|sick=아픔|sidebar=사이드바|sides=측면
sign=기호|signal=신호|signature=서명|silence=무음|sim=유심|simple=간단한|sin=사인|sine=사인파|sing=노래|singapore=싱가포르|sitemap=사이트맵|size=크기|skateboard=스케이트보드|skateboarding=스케이트보드 타기|skating=스케이트 타기|sketching=스케치|skew=기울이기|ski=스키|skip=건너뛰기|skull=해골|skyscraper=고층 건물|slash=슬래시|slashes=빗금들|sleigh=썰매|slice=조각|slideshow=슬라이드 쇼|small=작은|smart=스마트|smile=미소|smoke=연기|smoking=흡연|snooze=알람 미루기
snow=눈 날씨|snowboarding=스노보드|snowflake=눈송이|snowman=눈사람|soccer=축구|social=소셜|sock=양말|sofa=소파|solana=솔라나|solar=태양|som=솜|sort=정렬|sos=긴급 구조|soup=수프|source=원본|south=남쪽|space=공간|spaces=공백|spacing=간격|spade=스페이드|spark=불꽃|sparkle=반짝임|sparkles=반짝임들|spatula=뒤집개|speaker=스피커|speakerphone=스피커폰|speedboat=쾌속정|spellcheck=맞춤법 검사|sphere=구|spider=거미|spinner=회전 표시|spiral=나선
spline=스플라인 곡선|split=분할|spoon=숟가락|sport=스포츠|spray=분무기|spreadsheet=스프레드시트|sprint=단거리 달리기|spy=스파이|square=사각형|squares=사각형들|squint=실눈|stack=쌓기|stadium=경기장|staff=오선|stairs=계단|stamp=도장|star=별|starred=별표 표시|stars=별들|start=시작|station=역|stats=통계|status=상태|steam=증기|steering=운전대|step=단계|stereo=스테레오|stethoscope=청진기|sticker=스티커|stop=정지|stopwatch=초시계|store=상점|storm=폭풍
straight=직선|stretch=늘이기|stretching=스트레칭|strikethrough=취소선|stroke=선 두께|style=스타일|submarine=잠수함|subscript=아래 첨자|subtask=하위 작업|subtitles=자막|subtract=빼기|sum=합계|sun=태양|sunglasses=선글라스|sunrise=일출|sunset=일몰|superscript=위 첨자|surprised=놀람|suspension=현수|suv=스포츠 유틸리티 차량|swatch=색상 견본|swedish=스웨덴|swimming=수영|swipe=밀어서 이동|switch=스위치|sword=검|swords=검들|symbols=기호들|symlink=심볼릭 링크|syrup=시럽
tab=탭|table=표|tablet=태블릿|tabs=탭들|tag=태그|tags=태그들|tail=꼬리|taiwan=대만|taka=타카|tall=키 큰|tallymark=집계선|tallymarks=집계선들|tank=탱크|tape=테이프|target=목표|taurus=황소자리|tax=세금|tea=차|teacher=교사|teapot=찻주전자|telescope=망원경|temperature=온도|template=템플릿|tenge=텡게|tennis=테니스|tent=텐트|terminal=터미널|test=시험|tether=테더|text=텍스트|texture=질감|thai=태국|theater=극장|thermometer=온도계|thinking=생각
third=세 번째|thread=스레드|three=셋|thumb=엄지|ticket=표|tie=넥타이|tilde=물결표|tilt=기울기|time=시간|timeline=타임라인|timezone=시간대|tip=팁|to=도착점|toggle=전환|toilet=화장실|tongue=혀|tool=도구|tools=도구들|tooltip=툴팁|top=위쪽|topology=위상 구조|torch=횃불|torii=도리이|tornado=토네이도|tournament=토너먼트|tower=탑|toy=장난감|trace=궤적|traces=궤적들|track=트랙|tractor=트랙터|trademark=상표|traffic=교통|train=기차
transaction=거래|transfer=전송|transform=변환|transgender=트랜스젠더|transition=전환|trash=휴지통|travesti=트라베스티|treadmill=러닝머신|treasure=보물|tree=나무|treemap=트리맵|trees=나무들|trekking=트레킹|trending=추세|triangle=삼각형|triangles=삼각형들|trident=삼지창|triple=삼중|trolley=수레|trophy=트로피|trowel=모종삽|truck=트럭|tugrik=투그릭|tumble=회전 건조|tunnel=터널|turbine=터빈|turn=방향 전환|tv=텔레비전|twig=잔가지|two=둘|type=유형|typeface=글꼴|typography=타이포그래피
ufo=미확인 비행 물체|umbrella=우산|unamused=시큰둥함|underline=밑줄|unfolded=펼침|unicycle=외발자전거|union=합집합|universe=우주|unknown=알 수 없음|unlink=연결 해제|unlisted=목록에서 숨김|up=위쪽|upload=업로드|upper=대문자|urgent=긴급|user=사용자|users=사용자들|vaccine=백신|vacuum=진공|variable=변수|vault=금고|vector=벡터|venus=금성|versions=버전들|vertical=세로|vibration=진동|video=동영상|view=보기|viewfinder=뷰파인더|viewport=표시 영역|vignette=비네팅|vinyl=레코드판
vip=귀빈|virgo=처녀자리|virtual=가상|virus=바이러스|vision=시야|vocabulary=어휘|voice=음성|volcano=화산|volleyball=배구|voltmeter=전압계|volume=음량|walk=걷기|wall=벽|wallet=지갑|wallpaper=배경화면|wand=마법 지팡이|warehouse=창고|wash=세탁|watch=손목시계|waterpolo=수구|wave=파도|waves=물결들|webhook=웹훅|week=주|weight=무게|west=서쪽|wheat=밀|wheel=바퀴|wheelchair=휠체어|whirl=소용돌이|whisk=거품기|wide=넓은|width=너비|wifi=와이파이|wind=바람|windmill=풍차
window=창|windsock=풍향계|wink=윙크|wiper=와이퍼|woman=여자|won=원화|wood=나무 재료|word=단어|workstation=워크스테이션|world=세계|wrap=줄바꿈|wreath=화환|wrecking=철거|writing=쓰기|xbox=엑스박스|xnor=부정 배타적 논리합|xor=배타적 논리합|xrp=리플|yang=양|yarn=실타래|yen=엔|yin=음|yoga=요가|you=사용자|yuan=위안|zag=지그재그|zcash=지캐시|zener=제너|zeppelin=비행선|zero=영|zig=지그재그|zimbabwean=짐바브웨|zip=압축|zloty=즈워티|zodiac=별자리|zoom=확대|zzz=수면
`;
export const words = parseTerms(lines);
