import { test, expect } from '@playwright/test';
import { createRequire } from 'node:module';
import { readFile } from 'node:fs/promises';
import { setIconFilled, chooseIcon, iconCard, launchIcon, setIconSize } from './icons-docs-helpers';
import { clipboard } from './motion-docs-helpers';
// @ts-ignore The same packed consumer compiler checks copied examples.
import { prepareExample, compileEntries } from '../../../scripts/example-consumers.mjs';
import { iconPageSize } from './docs-data';
const require = createRequire(import.meta.url);
const alien = require('@kjun/icons/icons/alien'), rocket = require('@kjun/icons/icons/rocket');
const abacus = require('@kjun/icons/icons/abacus');
const { iconMetadata } = require('@kjun/icons/metadata');
test.describe.configure({ timeout: 180000 });
test('catalog and shape failures have separate retries and only visible shapes are requested', async ({ page }) => {
  let catalogFails = true, shapeFails = true;
  const requests = new Set<string>();
  await page.route('**/previews/icons/3.48.0/*.json', route => {
    const name = new URL(route.request().url()).pathname.split('/').at(-1)!;
    requests.add(name);
    return name === 'catalog.json' && catalogFails || name === 'abacus.json' && shapeFails ? route.abort() : route.continue();
  });
  await page.goto('/icons?platform=react');
  await expect(page.getByRole('button', { name: '검색 정보 다시 시도' })).toBeVisible();
  expect([...requests]).toEqual(['catalog.json']);
  catalogFails = false;
  await page.getByRole('button', { name: '검색 정보 다시 시도' }).click();
  await expect(page.locator('.icon-card')).toHaveCount(iconPageSize);
  await expect(page.getByRole('button', { name: '도형 다시 시도' })).toBeVisible();
  expect([...requests].sort()).toEqual(['catalog.json', ...iconMetadata.slice(0, 24).map((entry: any) => entry.name + '.json')].sort());
  shapeFails = false;
  await page.getByRole('button', { name: '도형 다시 시도' }).click();
  await expect(iconCard(page, 'abacus').locator('svg')).toBeVisible();
  await expect(iconCard(page, 'abacus').locator('svg path').first()).toHaveAttribute('d', abacus.outline[0][1].d);
  await expect(page.getByRole('button', { name: '도형 다시 시도' })).toHaveCount(0);
  await page.getByLabel('이름·한국어 용도 검색').fill('깃허브');
  await expect(iconCard(page, 'brand-github')).toBeVisible();
  await page.getByLabel('이름·한국어 용도 검색').fill(iconMetadata.find((entry: any) => entry.name === 'alien').tags[0]);
  await expect(iconCard(page, 'alien')).toBeVisible();
  // Official tags participate independently of the Korean label.
  await page.getByLabel('이름·한국어 용도 검색').fill('외계인');
  await expect(iconCard(page, 'alien')).toBeVisible();
});
test('slow previous shape requests cannot overwrite a new search or selection', async ({ page }) => {
  let release!: () => void;
  const held = new Promise<void>(resolve => { release = resolve; });
  await page.route('**/previews/icons/3.48.0/alien.json', async route => { await held; await route.continue().catch(() => {}); });
  await page.goto('/icons?platform=react');
  await chooseIcon(page, 'alien');
  await expect(page.getByText('현재 페이지의 아이콘을 불러오는 중입니다.')).toBeVisible();
  await chooseIcon(page, 'rocket');
  const root = await launchIcon(page);
  await expect(root.frameLocator('iframe').locator('svg path').first()).toHaveAttribute('d', rocket.outline[0][1].d);
  release();
  await expect(page.locator('.icon-name pre')).toHaveText('rocket');
  await expect(iconCard(page, 'rocket').locator('svg path').first()).toHaveAttribute('d', rocket.outline[0][1].d);
  await expect(root.frameLocator('iframe').locator('svg path').first()).toHaveAttribute('d', rocket.outline[0][1].d);
});
for (const platform of ['react', 'vue2', 'native']) test(`${platform}: additional filled icon retry and copied static registration run independently`, async ({ page }) => {
  await clipboard(page);
  let failFrame = true;
  const frameShapes = new Set<string>();
  page.on('request', request => {
    if (request.frame() !== page.mainFrame() && request.url().includes('/previews/icons/3.48.0/')) frameShapes.add(request.url().split('/').at(-1)!);
  });
  await page.route('**/previews/icons/3.48.0/alien.json', route => failFrame && route.request().frame() !== page.mainFrame() ? route.abort() : route.continue());
  await page.goto('/icons?platform=' + platform);
  await chooseIcon(page, 'alien');
  const root = page.locator('[data-guide-case="icons-selection"]');
  await root.scrollIntoViewIfNeeded();
  await expect(root.getByText('실행 화면을 불러오지 못했습니다.')).toBeVisible();
  failFrame = false;
  await root.getByRole('button', { name: '다시 시도', exact: true }).click();
  await launchIcon(page);
  await setIconSize(page, '24');
  await setIconFilled(page);
  await expect(root.locator('.guide-running')).toHaveAttribute('data-ready', 'true');
  await expect(root.frameLocator('iframe').locator('svg path').first()).toHaveAttribute('d', alien.filled[0][1].d);
  expect([...frameShapes]).toEqual(['alien.json']);
  await page.getByText('import·Provider 등록 예제', { exact: true }).click();
  await page.getByRole('button', { name: '등록 예제 복사', exact: true }).click();
  const code = await page.evaluate(() => (window as any).__motionCopies.at(-1));
  expect(code).toContain("import selectedIcon from '@kjun/icons/icons/alien'");
  expect(code).toContain('projectIcons');
  expect(code).not.toMatch(/loadIcon|\/previews\/|fetch\(/);
  const id = 'GuideIconSelection-full-icons-' + platform;
  const entry = await prepareExample(platform, 'GuideIconSelection', id, { name: 'alien', size: 24, filled: true }, {}, 'default', code);
  await compileEntries(platform, { [id]: entry });
  await page.route('**/previews/export-checks/**', async route => {
    const path = new URL(route.request().url()).pathname.split('/export-checks/')[1];
    await route.fulfill({ body: await readFile('artifacts/export-checks/' + path), contentType: path.endsWith('.html') ? 'text/html' : path.endsWith('.js') ? 'application/javascript' : 'text/css' });
  });
  const shapeRequests: string[] = [];
  const errors: string[] = [];
  page.on('pageerror', error => errors.push(error.message));
  page.on('request', request => { if (request.url().includes('/previews/icons/')) shapeRequests.push(request.url()); });
  await page.goto(`/previews/export-checks/${platform}/${id}.html`);
  await expect(page.locator('svg path').first()).toHaveAttribute('d', alien.filled[0][1].d);
  expect(shapeRequests).toEqual([]);
  expect(errors).toEqual([]);
});
