// Preserved default-icon language. Shapes and supported names come from packed @kjun-ui/icons.
export const iconLabels: [string, string, ...string[]][] = [
  ['adjustments', '세로 조절', '설정', '필터'],
  ['adjustments-horizontal', '가로 조절', '설정', '필터'],
  ['alert-circle', '원형 경고', '오류', '주의'],
  ['alert-triangle', '삼각 경고', '위험', '주의'],
  ['arrow-back-up', '되돌리기', '취소'],
  ['arrow-down', '아래 화살표', '내리기'],
  ['arrow-forward', '앞으로 보내기', '전달'],
  ['arrow-left', '왼쪽 화살표', '뒤로 가기'],
  ['arrow-right', '오른쪽 화살표', '다음'],
  ['arrow-up', '위 화살표', '올리기'],
  ['arrows-diagonal-2', '대각선 확대', '크기'],
  ['arrows-exchange', '교환', '전환'],
  ['arrows-maximize', '최대화', '확대'],
  ['arrows-minimize', '최소화', '축소'],
  ['arrows-sort', '양방향 정렬', '순서'],
  ['atom', '원자', '과학'],
  ['bell', '종', '알림'],
  ['bolt', '번개', '빠른 실행'],
  ['book', '책', '문서', '가이드'],
  ['border-style', '테두리 스타일', '선'],
  ['box', '상자', '패키지'],
  ['brand-docker', '도커', '컨테이너'],
  ['brand-telegram', '텔레그램', '메시지'],
  ['bug', '버그', '오류', '디버그'],
  ['building', '건물', '회사'],
  ['building-bank', '은행', '금융'],
  ['calendar', '달력', '날짜', '일정'],
  ['caret-up', '위 삼각형', '오름'],
  ['cash', '현금', '지폐'],
  ['chart-area', '영역 차트', '그래프'],
  ['chart-bar', '막대 차트', '그래프'],
  ['chart-candle', '캔들 차트', '주가', '봉'],
  ['chart-column', '열 차트', '그래프'],
  ['chart-line', '선 차트', '그래프'],
  ['chart-pie', '원형 차트', '비율'],
  ['check', '확인', '완료', '체크'],
  ['checklist', '체크 목록', '할 일'],
  ['checks', '이중 확인', '완료'],
  ['chess-knight', '체스 나이트', '전략'],
  ['chevron-down', '아래 꺾쇠', '펼치기'],
  ['chevron-left', '왼쪽 꺾쇠', '이전'],
  ['chevron-right', '오른쪽 꺾쇠', '다음'],
  ['chevron-up', '위 꺾쇠', '접기'],
  ['chevrons-left', '왼쪽 이중 꺾쇠', '처음'],
  ['chevrons-right', '오른쪽 이중 꺾쇠', '마지막'],
  ['circle', '원', '도형'],
  ['circle-check', '원형 확인', '성공'],
  ['circle-off', '원형 금지', '차단'],
  ['circle-plus', '원형 추가', '생성'],
  ['circle-x', '원형 닫기', '취소'],
  ['clipboard-list', '클립보드 목록', '기록'],
  ['clock', '시계', '시간'],
  ['code', '코드', '개발'],
  ['coins', '동전', '자산'],
  ['color-picker', '색 추출', '스포이트'],
  ['copy', '복사', '클립보드'],
  ['cpu', '중앙 처리 장치', '프로세서'],
  ['cube', '정육면체', '입체'],
  ['currency-bitcoin', '비트코인', '암호화폐'],
  ['currency-dollar', '달러', '통화'],
  ['currency-won', '원화', '통화'],
  ['database', '데이터베이스', '저장소'],
  ['device-desktop', '데스크톱', '모니터'],
  ['device-gamepad-2', '게임패드', '게임'],
  ['device-laptop', '노트북', '컴퓨터'],
  ['device-mobile', '휴대전화', '모바일'],
  ['device-tablet', '태블릿', '기기'],
  ['diamond', '다이아몬드', '보석'],
  ['dice', '주사위', '무작위'],
  ['door-enter', '문으로 들어가기', '입장'],
  ['dots', '가로 점 세 개', '더 보기'],
  ['dots-vertical', '세로 점 세 개', '더 보기'],
  ['download', '다운로드', '내려받기'],
  ['droplet', '물방울', '물'],
  ['edit', '편집', '수정'],
  ['external-link', '외부 링크', '새 창'],
  ['eye', '보기', '표시'],
  ['eye-off', '숨기기', '비공개'],
  ['feather', '깃털', '가벼움'],
  ['file-text', '텍스트 파일', '문서'],
  ['fish', '물고기', '바다'],
  ['flag', '깃발', '표시', '신고'],
  ['flask', '플라스크', '실험'],
  ['folder', '폴더', '디렉터리'],
  ['folder-open', '열린 폴더', '디렉터리'],
  ['gauge', '계기판', '속도'],
  ['globe', '지구본', '언어'],
  ['grip-vertical', '세로 손잡이', '드래그', '이동'],
  ['heart', '하트', '관심', '좋아요'],
  ['heartbeat', '심장 박동', '상태', '건강'],
  ['help-circle', '도움말', '질문'],
  ['hierarchy', '계층', '구조'],
  ['history', '기록', '내역'],
  ['home', '집', '홈'],
  ['id', '신분증', '식별'],
  ['info-circle', '정보', '안내'],
  ['key', '열쇠', '인증'],
  ['layers-intersect', '레이어 교차', '겹침'],
  ['line', '직선', '도형'],
  ['link', '링크', '연결'],
  ['list', '목록', '리스트'],
  ['list-numbers', '번호 목록', '순서'],
  ['loader-2', '로더', '로딩', '대기'],
  ['lock', '잠금', '보안'],
  ['lock-open', '잠금 해제', '보안'],
  ['logout', '로그아웃', '나가기'],
  ['mail', '메일', '이메일'],
  ['menu-2', '메뉴', '탐색'],
  ['palette', '팔레트', '색상'],
  ['pencil', '연필', '쓰기', '수정'],
  ['photo', '사진', '이미지'],
  ['player-pause', '일시 정지', '재생'],
  ['player-play', '재생', '시작'],
  ['player-stop', '중지', '정지'],
  ['plug', '플러그', '연결'],
  ['plus', '더하기', '추가'],
  ['pointer', '포인터', '선택'],
  ['qrcode', '큐알 코드', '스캔'],
  ['refresh', '새로고침', '갱신'],
  ['restore', '복원', '이전 상태'],
  ['robot', '로봇', '자동화'],
  ['rocket', '로켓', '출시'],
  ['ruler-measure', '측정 자', '크기'],
  ['satellite', '위성', '통신'],
  ['search', '검색', '찾기'],
  ['send', '보내기', '전송'],
  ['server', '서버', '호스팅'],
  ['settings', '설정', '환경'],
  ['shield', '방패', '보호'],
  ['shopping-cart', '장바구니', '구매'],
  ['slash', '빗금', '구분'],
  ['sort-ascending', '오름차순', '정렬'],
  ['sort-descending', '내림차순', '정렬'],
  ['star', '별', '즐겨찾기'],
  ['sun', '태양', '밝기'],
  ['table', '표', '테이블'],
  ['target', '표적', '목표'],
  ['template', '템플릿', '서식'],
  ['thumb-up', '엄지 올리기', '추천'],
  ['trash', '휴지통', '삭제'],
  ['trending-down', '하락 추세', '감소'],
  ['trending-up', '상승 추세', '증가'],
  ['trophy', '트로피', '수상'],
  ['typography', '글자', '서체'],
  ['user', '사용자', '계정'],
  ['user-cog', '사용자 설정', '계정'],
  ['user-shield', '사용자 보호', '권한'],
  ['vector', '벡터', '경로'],
  ['wallet', '지갑', '자산'],
  ['wand', '마술봉', '자동'],
  ['wave-sine', '사인파', '파동'],
  ['world', '세계', '국제'],
  ['x', '닫기', '취소'],
];
